

spring:
  server:
    port: 8080
    domain: 118.216.130.254

  spring:
    mvc:
      static-path-pattern: /static/**
    thymeleaf:
      mode: HTML
      encoding: UTF-8
      check-template-location: true
      prefix: classpath:/templates/
      suffix: .html
      cache: false
    resources:
      static-locations:
        - classpath:/static/
      cache:
        period: 0
